version: '3'
services:

  # Application Dockerfile
  app:
    build: .

  # Database Dockerfile
  world-db:
    build: db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "33060:3306"